name: Node.js Package (NPM)

on:
    workflow_dispatch:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.2.0
            - uses: actions/setup-node@v4.0.4
              with:
                  node-version: 24
            - run: npm install --force
            - run: npm run build

    publish:
        needs: test
        uses: Bracketed/Workflows/.github/workflows/Package-Publish.yml@main
        permissions:
            contents: write
            id-token: write
            actions: write
        with:
            project-name: '@bracketed/tsup-configuration'
            checkout-ref: main
        secrets:
            BRSFTWORKS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NODE_AUTH_TOKEN: ${{secrets.NODE_PUBLISH}}
